### ISSUE TITLE
"radius" field for user

### ISSUE THREAD

**Issue by abd-khrubi** [fouadhal/project#3]
Can you please add a `radius` field of type double for the user? 
thanks

**Comment by fouadhal** [comment]
It seems like you already did most of it, so I am not sure what you meant..
I've added it in the constructor and a function in FirebaseHandler

Let me know if you meant something else

**Comment by abd-khrubi** [comment]
For some reason, I'm only getting 0 for the radius,  so maybe I've done something wrong there.  Can you check it out?

**Comment by fouadhal** [comment]
Did you test it again after what I changed? (pushed into Client-Side)
Radius value wasn't set in the constructor, so when it does toObject it wouldn't set the radius..

I wanted to test it out but I couldn't get past the Map screen, it crashes when I tap on List view

**Comment by abd-khrubi** [comment]
I haven't tested it yet. 

The crash is related to location permission I think, I fixed that and I'll be pushing it tomorrow
